### ISSUE TITLE
Error when compiling libraries with ghdl

### ISSUE THREAD

**Issue by csantosb** [OSVVM/VerificationIP#4] opened 2020-06-18 15:54 UTC
Hello Jim,

  I’m trying to compile the `osvvm` and `verificationip` libraries with help of `ghdl`. I’m using archlinux os, along with [aur/ghdl-gcc-git](https://aur.archlinux.org/packages/ghdl-gcc-git/) (latest in master) package.

  I proceed by using ghdl’s provided vendors [script](https://github.com/ghdl/ghdl/blob/master/libraries/vendors/compile-osvvm.sh), which I adapt to each of the verification ips by just updating the `filelist`, the `library` name and the `ScriptDir`. You may see the resulting scripts [here](https://gitlab.com/ip-vhdl/eda-common/-/tree/master/ghdl/vendors).
     
  Upon running the `runme.sh` script, I manage to compile with no issue `osvvm` and the `verificationip/common` libs. Then, I get issues with `verificationip/uart` and `verificationip/axi4`. You may see the output [here](https://gitlab.com/ip-vhdl/eda-common/-/jobs/600208368).

  I’m wondering if I’m doing something wrong here, or if this is the expected behavior. Maybe this is a @ghdl issue, @tgingold ?

Thanks,

C.

**Comment by tmeissner** [comment] 2020-06-18 16:43
Maybe it has something todo with ghdl/ghdl#1373?

**Comment by JimLewis** [comment] 2020-06-18 19:36
In UartTx.vhd, it was this line:
    variable Operation : TransactionRec.Operation'subtype ;

In UartRx.vhd, it was this line:
    variable Operation : TransactionRec.Operation'subtype ;

Both of these can be worked around without too much pain.  

However, 'subtype of this form is needed in Axi4Lite to determine the size of unconstrained elements.   AxiStream avoids if for the time being as the interface was not abstracted into a record, but probably will be in the not too distant future.

**Comment by csantosb** [comment] 2020-06-19 14:48
Thanks @tmeissner, I tried the fix, but nothing changes. I guess this is mostly related to ghdl/ghdl#641, and so a ghdl issue.

**Closed as completed** 2020-06-19 14:50 UTC

**Comment by csantosb** [comment] 2020-06-26 07:30
Just for the record, as for right now, latests commits to ghdl fix the problem with the `verification/uart` library. Not yet with `verification/axi4`.

**Comment by JimLewis** [comment] 2020-06-28 20:12
Any indication if GHDL has accepted this as a bug or do they think that what they are doing with respect to aliases is correct.

**Comment by tgingold** [comment] 2020-06-29 04:52
Yes, I am improving the support of subtype attribute.

**Comment by JimLewis** [comment] 2020-06-29 04:58
Thanks Tristan.

**Comment by csantosb** [comment] 2020-06-29 16:39
Updated [link](https://gitlab.com/ip-vhdl/eda-common/-/jobs/616140568) to current ghdl version (as for 2020.06.27, GHDL 1.0-dev (v0.37.0-789-ge2d751d6) ) outcome when compiling verification ip library: only `axi4` fails. Hope this helps.

**Comment by JimLewis** [comment] 2020-07-11 17:50
@csantosb   I just pushed the dev branch of Verification IP (it is called docs).   Axi4Lite has not been updated yet - but I have added AXI4 Full pre release.   In the AXI4 Full, Axi4Master.vhd, I have made numerous changes that I suspect will address the 'subtype issue.   

It would be helpful to know as I am going to make the same changes to Axi4Slave_transactor.vhd as well as Axi4Memory.vhd.   I will be making the changes anyway what I did in the Axi4Master.vhd avoids having one alias per AXI interface signal (which was ugly).   

It is most likely that Axi4Lite will be a mode of the Axi4 model and will go away as a stand-alone model.   Not sure I need to keep the Axi4Lite around after AXI4 Full is stable.

**Comment by csantosb** [comment] 2020-07-11 22:00
@JimLewis I have updated the [compilation](https://gitlab.com/ip-vhdl/eda-common/-/blob/testing-verificationip/.gitlab-ci.yml) [scripts](https://gitlab.com/ip-vhdl/eda-common/-/tree/testing-verificationip/ghdl/vendors). I get [these](https://gitlab.com/ip-vhdl/eda-common/-/jobs/634490719) errors. Not sure I'm doing the correct thing, though.

**Comment by JimLewis** [comment] 2020-07-11 22:14
@csantosb   
Sorry.   I did not do a clean build after I made a modification to Common/AddressBusTransactionPkg and I missed the compile error.

I readded the alias to Common/AddressBusTransactionPkg.vhd.   It at least compiles in one simulator

**Comment by JimLewis** [comment] 2020-07-11 22:17
@csantosb
Also skip AxiStream for now.   I will be updating that one next.   What I really need to know is if Axi4/Axi4/Axi4Master.vhd 
compiles or not.   Axi4Memory and Axi4Slave_Transactor probably will not compile in GHDL yet.

This is like threading a needle through issues in multiple simulators (I currently test on two).

**Comment by JimLewis** [comment] 2020-07-11 22:24
Also skip Axi4Lite.   I have been working on Axi4/Axi4/Axi4Master.vhd - the Axi4 Full master.   I made changes in this one that I hope work for GHDL.

**Comment by csantosb** [comment] 2020-07-12 10:06
[Updated](https://gitlab.com/ip-vhdl/eda-common/-/commits/testing-verificationip) Note that you have a couple of files with uppercases around. Compilation is [here](https://gitlab.com/ip-vhdl/eda-common/-/jobs/634739794).

**Comment by JimLewis** [comment] 2020-07-12 13:17
@csantosb  Thanks for the latest batch of info.

I have updated Axi4/common/Axi4InterfacePkg and Axi4LiteInterfacePkg to address the compile issues.   Once more GHDL finding issues not found by commercial simulators.   This should address many of the issues.

WRT uppercases, are you thinking of AXI4.pro?  or Axi4LIteContext.vhd (where the I should not be uppercase)?
Currently if the *.pro files match the directory name, they do not need to be specified - it is in the AXI4 directory.
The OSVVM build scripts are pretty simple, so I don't know if it would find Axi4.pro or not.

**Comment by csantosb** [comment] 2020-07-12 14:49
@JimLewis You forgot to update main repo to follow latest change in AXI4 ?

By uppercase I meant [this](https://gitlab.com/ip-vhdl/eda-common/-/commit/9c7a6ebd203fad5d685a1a320105a6994b382fae)

**Comment by JimLewis** [comment] 2020-07-12 17:35
@csantosb   Probably missed pushing VerificationIP.   I did another push couple of minutes ago - and double checked on GitHub - it at least looks right.   I have now also updated Axi4Slave_Transactor.vhd.   

I fixed the case issues in Axi4Lite, however, I have not updated those files yet.   I need to look at what to do for Axi4Lite since we now have Axi4 full.

**Comment by csantosb** [comment] 2020-07-12 21:16
@JimLewis Commits look fine now. 

You'll find the compile results [here](https://gitlab.com/ip-vhdl/eda-common/-/jobs/635015374), including a couple of ghdl crashes. Remember this is 9th July ghdl with gcc as a backend.

**Comment by JimLewis** [comment] 2020-07-12 21:20
@csantosb  Did you catch the commits I just did?  I just updated AxiStream to use the common/StreamTransactionPkg.

**Comment by csantosb** [comment] 2020-07-12 21:44
@JimLewis Now it [is](https://gitlab.com/ip-vhdl/eda-common/-/jobs/635025029). 

Notice that I include the list of the latest commits by repo (line 77 for example) to be sure compilation is doing the right thing.

**Comment by JimLewis** [comment] 2020-07-12 21:44
It looks like you ran your tests just after I pushed the updates for AxiStream.  Note there were some package changes.

Do you have any insight to any work arounds for Axi4InterfacePkg.  

I need to meditate on Axi4Lite and decide what to update and what to just use from Axi4 Full.

**Comment by csantosb** [comment] 2020-07-12 22:07
> It looks like you ran your tests just after I pushed the updates for AxiStream. Note there were some package changes.

One [more](https://gitlab.com/ip-vhdl/eda-common/-/jobs/635029300) to be sure.

> Do you have any insight to any work arounds for Axi4InterfacePkg.

Sometimes with ghdl it is just a matter of a trial and error process: writing things a bit differently usually fixes the problem; launching compilation frequently to detect errors as soon as possible, automatizing the scripts with any commit to avoid regressions, and in the last term, grab a bug issue upstream with a simple example reproducing the problem. Tristan is rather reactive. Other than this, I'd say using a fixed docker environment to develop is a good idea: this is what I'm doing [here](https://gitlab.com/ip-vhdl/eda-common/-/blob/testing-verificationip/.gitlab-ci.yml). Then, from time to time, I update the environment and check everything is ok. This is how I proceed to avoid becoming crazy.

**Comment by JimLewis** [comment] 2020-07-13 01:04
There is alot of issues with record ports.   It has been like threading a needle with the commercial tools to get things running.  It is surprising, I actually thought they were more stable in this area.

**Comment by JimLewis** [comment] 2020-07-15 20:50
@csantosb   I just did another push, hoping to find the root of GHDL issues with Axi4InterfacePkg.vhd.   
I think it is something to do with the the subtypes Axi4RecType and Axi4LiteRecType.   Both had unconstrained fields unspecified, so I marked those as open rather than leaving them unspecified.   I also removed Axi4LiteRecType as it has null arrays for fields not used for Axi4Lite.   

Up for another try at it?

**Comment by csantosb** [comment] 2020-07-16 07:38
@JimLewis Sure, here we [go](https://gitlab.com/ip-vhdl/eda-common/-/jobs/641479174)

**Comment by JimLewis** [comment] 2020-07-16 17:48
@csantosb  That clairifies things.    Apparently GHDL does not yet support declaring a subtype of a partially constrained record.

I just pushed a new version of Axi4/Axi4InterfacePkg.vhd and Axi4/Testbench/TbAxi4.vhd that remove the subtypes and do the subtype constraints in the signal declarations.   Hopefully this does it.

I still have work on Axi4Lite.   I will get that done shortly.   It will involve moving some packages from Axi4 to common.

**Comment by csantosb** [comment] 2020-07-16 20:35
@JimLewis One [more](https://gitlab.com/ip-vhdl/eda-common/-/jobs/642932469). Indeed, things seem getting better.

**Comment by csantosb** [comment] 2020-07-16 23:05
@JimLewis Aside question. Is the ieee sa repo going to be a permanent home for osvvm, replacing this one ? If this is the case, maybe automatizing the process of compiling the libraries with ghdl using gitlab's ci is a good idea. What do you think ?

**Comment by JimLewis** [comment] 2020-07-16 23:15
@csantosb  Having a CI I could run would be great.   IEEE repo is not quite ready yet.   I just asked that yesterday.   

 IEEE SA repo will supplement GitHub.   To be compliant with IEEE, we had to change licenses.   No problem.  However, to host with IEEE we had to remove all revision history except for the versions with Apache license.   Hence, loosing all history.     It looks like any development done on GitHub will need to be copied over to the IEEE releases - currently thinking of using rsync.

**Comment by JimLewis** [comment] 2020-07-20 13:55
@csantosb  Did you file bug reports for the GHDL crashes?

The one that crashes due to the following is a big problem.   Many models use this technique.   It is fundamental to simple use of the FIFOs.    I can probably work around it - in cases like the following (from Axi4Lite) it could be replaced by two pushes and two pops.   However, in AXI full, probably not.   Likewise as I work on AxiStream, it is going to need numerous ones too.   
(WriteAddr, WriteProt) := WriteAddressFifo.pop ;

I have pushed everything onto the development branch.   I also added the OsvvmLibraries repository which has everything, including osvvm (utility library) and the documentation, as a submodule.   With the addition of OsvvmLibraries, VerificationIp is deprecated and will not be maintained.

**Comment by csantosb** [comment] 2020-07-20 17:50
@JimLewis Updating the compile scripts right now. Is line [41](https://github.com/OSVVM/AXI4/blob/70a3e91f730bde387d9f7067bb89740417392058/AXI4.pro) correct ?

**Comment by JimLewis** [comment] 2020-07-20 18:51
@csantosb  Yes, but it is probably the wrong place to call it at.   It will probably be removed in a future revision (either common/common.pro or the entire script as I mostly skip it).  That script was specialized to verify just the AXI models.   

A better reference is OsvvmLibraries.pro.   It skips calling Axi4/Axi4.pro.   Then if they compile, the files from the testbench can be build in the order defined in <path-to-testbench>/testbench/testbench.pro.

**Comment by csantosb** [comment] 2020-07-20 20:31
@JimLewis Sorry, I meant the master branch. There is no OsvvmLibraries.pro in there. [This](https://gitlab.com/ip-vhdl/eda-common/-/jobs/647502456) is what we get now using OsvvmLibraries/master.

**Comment by JimLewis** [comment] 2020-07-20 21:00
@csantosb Thank you.   That looks encouraging and helps immensely.  

Interesting, AxiStream works on what I thought the root cause of the issue is.   

The root issue must be related to subtype information not being available in GHDL.    I will try again later this week.   Maybe if I change some things to use 'range rather than depending on GHDL getting the information from the elaborated design, it will work.    

I will also start to work on those "hide" issues.   Don't want flags like that turned on.

**Comment by csantosb** [comment] 2020-07-20 21:14
@JimLewis And here you have for the OsvvmLibraries/dev [branch](https://gitlab.com/ip-vhdl/eda-common/-/jobs/647601158).

Please realize that the only difference in the compile [script](https://gitlab.com/ip-vhdl/eda-common/-/blob/testing-verificationip/ghdl/vendors/runme.sh) (other than the file list) between the two cases (master and dev) is the `--branch=dev` flag, as I'm not pulling changes from submodules. I guess this is what is expected.

**Comment by csantosb** [comment] 2020-07-20 21:16
@JimLewis As for filing a bug report for the GHDL crashes, I didn't. Easiest would be to delimit a simple case where it happens, issuing then a report.

**Comment by csantosb** [comment] 2020-07-22 09:49
@JimLewis I have finally setup a mirror [repository](https://gitlab.com/ip-vhdl/osvvmlibraries) in gitlab.com. In there, a couple of branches `dev-ci` and `master-ci` will include the compilation scripts and the ci stuff for checking your updates, along with the resulting [logs](https://gitlab.com/ip-vhdl/osvvmlibraries/-/pipelines). Hope it helps.

**Comment by JimLewis** [comment] 2020-07-22 21:40
@csantosb I pushed changes to Axi4LiteMaster, Axi4LiteResponder_transactor, and Axi4LiteMemory.    I am hoping these address the issues with AXI.  

I also pushed a couple of minor updates to AlertLogPkg and CoveragePkg.   This will fix some of the Hide issues.   However, I looked at the one that is reacting to WEIGHT.   Can't change that.   It is legal code.   GHDL is just being overly cautious - just like some simulators complain about legal usage of NULL arrays.

Is there a way I can start the CI?

**Comment by csantosb** [comment] 2020-07-22 22:50
@JimLewis Please check the [pipelines](https://gitlab.com/ip-vhdl/osvvmlibraries/-/pipelines) for results.

Sure, you can. Let me know if you have a user in there, I'll provide you access to the repo. Once done:
- wait until sync in `master`/`dev` branches happens, or do it manually
- pull locally all branches
- merge `dev-ci` with `dev` (same for `master`, if necessary); never modify `master`/`dev` branches
- push your modifications to `-ci` branch

`-ci` branches include a `ghdl_build_scripts` directory, with one script by submodule, think updating the filelist if necessary. Other than this, the ci should start automatically.

**Comment by JimLewis** [comment] 2020-07-23 16:54
@csantosb   Quick update, it looks like the below issue is just my misunderstanding of how submodules work.  

--------------
@csantosb Something went wrong with the build.   It looks like dev loaded older sources.   I can see the correct links on GitHub.
Also the heads are detached - however I talked to Patrick about that and he said that is normal for submodules.

Best Regards,
Jim

**Comment by JimLewis** [comment] 2020-07-23 18:46
@csantosb   Quick update, continued.   

Now that I know to expect detached heads with submodules, I have checked the hash in the build of dev and the right ones were select.

Does GHDL have a newer release that will work with some of the subtype stuff?   I think I can get the last of it from Axi4Lite, however, it is going to be real tedious to do it for Axi4 full.    

RANT mode on.   Going further, it is frustrating as subtype information like 'length is available - just 'subtype is not.   RANT mode off.

**Comment by csantosb** [comment] 2020-07-23 22:02
@JimLewis I understand the build is using the correct release ? Please confirm. I'm using precisely the line

    git status && git log -n4 --decorate --graph --oneline

to check this point in case of doubt. 

We're using here [this](https://gitlab.com/csantosb/dockerfiles/-/raw/master/arch-vhdl/Dockerfile) dockerfile as testing environment, so `gcc-ghdl nightly` from the 2020.07.20. Doesn't seem there is anything new since.

Wouldn't it be easier to provide a case as simple as possible reproducing the issue ? We could then submit it to ghdl and expect they fix it.

**Comment by JimLewis** [comment] 2020-07-23 23:42
@csantosb  Yes.  The build used the correct release.   

Just pushed a new release with no subtypes.   

WRT, GHDL, AFAIK, Tristan knows about subtype issues.

**Comment by csantosb** [comment] 2020-07-24 08:24
@JimLewis New [job](https://gitlab.com/ip-vhdl/osvvmlibraries/-/jobs) available just now.

**Comment by JimLewis** [comment] 2020-07-24 16:07
@csantosb  Thanks.   Axi4Lite compiles in GHDL!!!!

Over the weekend I will meditate on Axi4 Full.   I suspect by Monday I will have that one set too.

**Comment by JimLewis** [comment] 2020-07-27 16:46
@csantosb  Just pushed on the dev branch.   Removed 'subtype from Axi4 Verification Components.   It is ugly, but not as bad as I feared.

**Comment by csantosb** [comment] 2020-07-28 07:36
@JimLewis Just updated the [ci](https://gitlab.com/ip-vhdl/osvvmlibraries/-/pipelines)
